dependencies.gradle
dsl/build.gradle
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachine.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachineTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/StateMachine.kt
gradle.properties
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux/sample/shared/PaginationStateMachine.kt

make FlowReduxStateMachine based on StateFlow

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt

Builds on top of #169. The issue is basically the same as point 2 described in that pr, but this time the race condition is directly in the reduxStore operator.
The implementation of the dsl will emit the internal InitialStateAction in onStart. The issue was that this in some cases didn’t reach the side effects after going through the reducer. The reason for that is a race condition when setting up all the flows. The merge operator will internally do a launch for each given Flow and start collecting them in there. That works fine and is ordered. However I was able to observe that the collect going up the side effect chain can sometimes be slower than the subscription to the upstream actions.
In that case the timeline was:
1. start collecting sideeffects and upstream
2. reducer receives …

fix race condition in reduxStore

---

dependencies.gradle
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CustomIsInStateDslTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachineTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/FlowReduxTest.kt

Changelog:
https://github.com/cashapp/turbine/blob/trunk/CHANGELOG.md#060

Update to turbine 0.6.0

---

README.md
gradle.properties

I cannot push to master directly, so this needs to go through a PR.
Preparing stuff for 0.12.0 release (version number changes)

Release 0.12.0

---

build.gradle
compose/api/compose.api
compose/build.gradle
flowredux/api/flowredux.api
gradle/libs.versions.toml
sample/android/build.gradle
sample/android/src/main/AndroidManifest.xml

Lets us spot breaking api changes and missing/additional dependencies

add dependency analysis and binary compatibility plugins

---

.github/workflows/ios-build.yml
sample/ios/ios.xcodeproj/xcshareddata/xcschemes/ios.xcscheme

Closes #353 
I have checked it, it worked as expected: https://github.com/hoc081098/FlowRedux/actions/runs/3019841020

ci: add ios-build.yml to build iOS sample

---

compose/src/main/java/com/freeletics/flowredux/compose/ComposeFlowReduxStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStoreBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/flow/FlatMapWithExecutionPolicy.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/CollectInStateBasedOnStateBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/CollectInStateBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/OnActionInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/OnEnterInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/StartStateMachineOnActionInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/StartStatemachineOnEnterSideEffectBuilder.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/FlowReduxTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CustomIsInStateDslTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachineTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/StartStateMachineOnActionInStateTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/StateMachine.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/SubStateMachineTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/internal/SubStateMachinesMapTest.kt
gradle/libs.versions.toml
sample/android/build.gradle
sample/shared_code/build.gradle
settings.gradle

It's still in beta but I'm fine with waiting for it to go stable before doing a flowredux release. With this we don't need FlowPreview anymore.

coroutines 1.7.0

---

compose/compose.gradle
flowredux/flowredux.gradle
gradle/libs.versions.toml

use fgp publish plugin

---

sample/ios/ios.xcodeproj/project.pbxproj
sample/ios/ios/ContentView.swift
sample/ios/ios/ErrorView.swift
sample/ios/ios/GithubReposList.swift
sample/ios/ios/GithubRepositoryRow.swift
sample/ios/ios/LoadingIndicatorView.swift

Just a few small changes here and there to the iOS sample project, mainly adding more previews and slightly enhancing syntax.
Also added an error view and used it whenever an error state is emitted.

minor iOS sample improvements

---

.gitignore
flowredux/flowredux.gradle
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/SubStateMachineTest.kt
flowredux/src/jsMain/kotlin/com/freeletics/flowredux/dsl/util/AtomicCounter.kt

add js target

---

docs/dsl.md

Issue reported in https://github.com/freeletics/FlowRedux/issues/469 - ClassCastException with no using snapshot

Updated dsl.md - fixed unit test part (#474

---

.editorconfig
.github/workflows/build.yml
.kts/ktlint.main.kts
build.gradle
docs/contributing.md
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStoreBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/StartStateMachineOnActionInStateSideEffectBuilder.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/StartStateMachineOnActionInStateTest.kt
gradle/libs.versions.toml
kotlinw
sample/android/src/main/java/com/freeletics/flowredux/compose/ReposListUi.kt
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux/sample/shared/MarkAsFavoriteStateMachine.kt
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux/sample/shared/PaginationStateMachine.kt

To keep things aligned this is now using our ktlint script instead of the Gradle plugin.

switch ktlint to kts script

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectWhile.kt

Since it doesn't need to care about state changes anymore thanks `ManagedSideEffect`, the regular `collectWhileInState`  can now just collect the given flow directly without needing anything else. Because of that it can directly use `SideEffect` where forwarded state changes and actions are just swallowed.

refactor CollectWhile side effect

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectWhileBasedOnState.kt

Fairly similar to #510. The main difference is that it does consume state changes so that it can build the collected flow based on the current state. 
I initially introduced a base class for this state collecting behavior but then got rid of it again because this is the only side effect that needs it and as part of #186 this one will be deprecated meaning that in an eventual 2.0 it won't exist anymore at all.

refactor CollectWhileBasedOnState side effect

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/BaseBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnEnterStartStateMachine.kt

This uses the `initialState` parameter from the builder now and `ActionBasedSideEffect` to get the actions that it needs to forward.

refactor OnEnterStartStateMachine side effect

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnActionStartStateMachine.kt

Compared to the other ones this one didn't change too much. It is also an `ActionBasedSideEffect` now and the `whileInState` is gone now.

refactor OnActionStartStateMachine side effect

---

.github/workflows/build.yml
.github/workflows/ios-build.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml

The Gradle action now has a new name with v3. Also remvoes the hash that renovate added for the checkout action

update Github Actions

---

gradle/libs.versions.toml

The ktx artifact is now empty.

replace activity-ktx with activity artifact

---

flowredux/api/flowredux.api
flowredux/flowredux.gradle.kts
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/BaseBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/FlowReduxStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/OnActionStartStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterStartStateMachine.kt
gradle/libs.versions.toml

Since we're breaking binary compatibility in 2.0 we can finally switch the dependency

use khonshu statemachine

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/BaseBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/ChangeableState.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/ReduxStore.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/SideEffect.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/CollectWhileEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnActionEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterEffectTest.kt

skip state emission for effect handlers
