freeletics/FlowRedux

library/build.gradle
library/src/main/kotlin/com/freeletics/flowredux/FlowRedux.kt
library/src/main/kotlin/com/freeletics/flowredux/ReducerException.kt
library/src/main/kotlin/com/freeletics/flowredux/SideEffect.kt

`@FlowPreview` will make propagate the experimental warning to consumers of `reduxStore`. The warnings for using BroadcastChannel are suppressed because we only use it internally, meaning that consumers don't have to opt in to using `ExperimentalCoroutinesApi`.

add FlowPreview and UseExperimental annotations

---

library/src/main/kotlin/com/freeletics/flowredux/FlowRedux.kt

The issue was that the loop does not continue until the collect on the first one completes.
E.g.:
```
Emitting initial state
STATE: Start
Subscribing upstream
Subscribing sideeffect
Received action 1 from upstream
STATE: Start1
-- SF1: Got action 1 . current state Start1
Got action 3 from sideeffect
STATE: Start13
-- SF1: Got action 3 . current state Start13
-- SF1: Got action 1 . current state Start13
Got action 3 from sideeffect
STATE: Start133
-- SF1: Got action 3 . current state Start133
Received action 2 from upstream
STATE: Start1332
Completed upstream
-- SF1: Got action 2 . current state Start1332
Got action 3 from sideeffect
STATE: Start13323
-- SF1: Got action 3 . current state Start13323
-- SF1: Got action 2 . current state Start13323
Got action 3 from sideeffect
STATE: …
```

fix only the first SideEffect getting called

---

dependencies.gradle
library/build.gradle
library/src/main/kotlin/com/freeletics/flowredux/FlowRedux.kt
library/src/test/kotlin/com/freeletics/rxredux/FlowReduxTest.kt

This fixes:
- receiving actions twice in side effects
- subscribing to the upstream twice
- returned Flow does not always complete when upstream completes
Open issues:
- SideEffects are called in a weird order (see the last two tests which are failing).
- When upstream completes SideEffects are not run on actions emitted by SideEffects in response to the last upstream action. So if upstream emits a `2`, the `2` is going through the reducer and the SideEffects. When a SideEffect emits an action in response to the `2` that action will go through the reducer, but not again to SideEffects. The cause for this is the BroadcastChannel being closed so send isn't working anymore. I'd say that this isn't a big issue because for redux use cases the upstream usually never completes.

 only subscribe once to upstream, properly terminate

---

library/src/test/kotlin/com/freeletics/flowredux/FlowReduxTest.kt

The test is still ignored because the current implementation.

fix expected side effect actions in test

---

README.md

In the README example, we are setting the state with `state.value = newState` which is only possible with `MutableLiveData`. Therefore we have to change the type from `LiveData` to `MutableLiveData`.

Fix LiveData type in README

---

dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/Dsl.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/FlowReduxTest.kt

This replaces the internal usages of channels by just merging the upstream actions and the actions emitted by side effects into one flow that than is collected. I'm not sure about all the issues that we had in the past before going to `select` and `onReceive` but back then we also used `launch` internally which we don't need here. Also collecting a `Flow` inside the `flow {}` builder is fine, so I think  this implementation should work.
There is one behavior change. Previously we had essentially 2+ action queues, one for actions coming from upstream and one  each for actions emitted by each side effect. The side effect action queues were always handled first and only if they were empty we would look at the next upstream action. Also within the side effects there was strict ordering by …

remove Channels from the reduxStore implementation

---

dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CustomIsInStateDslTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachineTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterTest.kt

The tests were generally not running correctly because runBlocking is not transitive. So if we `launch` inside the test to call `sm.state.test {}` nothing waits for that test block to finish. It just gets cancelled. This is most noticeable in the places where we had `expectComplete()`. The `Flow` returned by `reduxStore` (even without DSL) never completes, which shows those tests didn't actually fully run before.
The bad news is that the cancellation tests still work even though they shouldn't. Switching the dispatcher does break them but it also breaks tests that shouldn't break.I will look into that more.

fix tests to some degree

---

dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterTest.kt

Builds on top of #169.
With all the other stuff out of the way I was now finally able to reproduce #128 in tests. Now that it's running asynchronously all that needed to be done is moving the `assertFalse` for reached down. Similar to case 3 in #169 the assertion happened before the action was processed in the state machine so `reached` was still `false` but it would change a bit later. It would have been enough to move them one line down after the next `expectItem` but I moved them to the end where they should always work.
Unfortunately I still can't break a test for #166/collectWhileInState.

break OnAction and OnEnter canellation tests

---

dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/CollectInStateSideEffectBuilder.kt

Each when branch was identical except for the inner `flatMap...` call. Since we already have `flatMapWithPolicy` I've changed the inner flatMap to that and removed the when.
Also updates the name of the class because it's the only implementation by now.

deduplicate CollectInState code, update name

---

docs/dsl.md
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/OnEnterInStateSideEffectBuilder.kt

Closes #171 and adresses the onEnter part of #128.
The old `flatMapWithPolicy` didn't get any events when leaving the state which is why it didn't cancel even if it was using `LATEST`. The new implementation turns each action emission to an `isInState` boolean and then has a `flatMapLatest` that will only return the onAction Flow if the boolean was true. This way the previous `Flow` will get cancelled when `isInState` changes from true to false. `distintUntilChanged` is used to ignore any additional emissions after the first `true`.
Instead of `map` to a boolean and `distintUntilChanged` this could also use `filterState` from the `CollectWhileInState` implementation. However this seems a lot less complex to me and I can't think of any issues with this implementation.

remove onEnter flatMapPolicy and fix cancellation when leaving state

---

dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/Dsl.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachine.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/flow/WhileInState.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/OnActionInStateSideEffectBuilder.kt

Closes #128 
This one is more complex then fixing onEnter. Just the boolean that we have there because we still need the action value and new actions while we are in the state should not cancel the previous flow. We basically want a `flatMapSometimesLatest`. The new operator will put new upstream actions into a `Channel` when `isInState` is true. This `Channel` is then turned into a Flow and we apply our filtering and transformation with the flatMapPolicy on it. The resulting `Flow` gets collected and it's emissions are emitted to the downstream. When `isInState` becomes false the channel is closed so that the resulting flow will get cancelled as well.

cancel onAction when leaving the current state

---

docs/dsl.md
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/Dsl.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachine.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/flow/WhileInState.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/OnActionInStateSideEffectBuilder.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/OnEnterInStateSideEffectBuilder.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/StateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt

This replaces the dispatcher used in tests with `Dispatchers.Default`. There was a combination of things at play here.
1. Initial state is now visible to all tests again, this was expected from me. I only removed those expects in #130 because I had to use Unconfined
1. Any test that relied on a dispatched action for the first state change (`OnActionTest` and `CustomIsInStateDslTest`) was affected by an issue in `FlowReduxStateMachine`. Because of the launch that is done to start the store and it using `MutableSharedFlow` for incoming actions, any action that is dispatched before the launch body executes was lost. So the tests relying on an action didn't work. In real world use cases this is probably not an issue because you don't start dispatching actions a few millisecods later. I've …

fix issues hidden by Unconfined Dispatcher

---

.github/workflows/build.yml

Could also be stored as Artifacts, but in the long run I would rather like to have another integration that is able to pars the HTML properly (if XML reports cannot be created for multiplatform) and solve the problem that way (rather than spending time to setup storing artifacts)

Print HTML Report for unit test result to console on CI

---

.github/workflows/build.yml

Just printing on console `index.html` doesnt help as there are "sub hmtl" pages created for each failing task. Therefore, let's introduce to upload the full `build/reports/tests/allTests` folder and then one can download it from github actions ...

upload  test report as artifacts if CI fails

---

dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/flow/MapToIsInState.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/CollectInStateSideEffectBuilder.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/OnEnterInStateSideEffectBuilder.kt

It now uses the same implementation as `onEnter` to detect entering and leaving the state.
I think we could even go further and remove the extra builder and use the `CollectInStateBasedOnStateSideEffectBuilder` also for this one. The given `Flow` can be converted into a flowBuilder like this `{ currentStateFlow -> currentStateFlow.take(1).flatMapLatest { flowPassedInByUser }`.

simplify CollectInStateSideEffectBuilder implementation

---

docs/dsl.md
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/EffectHandlers.kt
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateEffectTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionEffectTest.kt
dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterEffectTest.kt

adds
- `onActionEffect<Action>` 
- `onEnterEffect`
- `collectWhileInStateEffect` 
which behave (in the sense of cancelation) the same way as their counterparts.

Adds Effects as counterpart to existing DSL primitives

---

dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/CollectInStateBasedOnStateSideEffectBuilder.kt

I can't reproduce it in tests but it happened a few times in a state machine that is very busy (multiple actions per second) after some time. I assume there are cases where the state changes right before the flow reaches map. Using a safe cast with mapNotNull here should be fine as any change state would no-op anyways because of later state checks.
In general this is probably another reason to rethink the internals and make state changes more of a primary thing instead of having it purely based on action emissions that happen afterwards

fix crash in flowBuilder based collectWhileInState

---

build.gradle
dependencies.gradle
dsl/build.gradle
dsl/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/InStateSideEffectBuilder.kt
flowredux/build.gradle

Fixes #199.
Temporarily using`com.freeletics.mad:state-machine:0.3.0-SNAPSHOT` (testing locally) until [this](https://github.com/freeletics/mad/pull/11) merged and released.
Remaining dependencies missing apple silicon targets:

Add Apple Silicon targets

---

.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml

With Kotlin 1.6.0 it's possible to build the windows artifacts on macOS so we can build everything there for publishing.

publish everything from macOS

---

compose/src/main/java/com/freeletics/flowredux/compose/ComposeFlowReduxStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/Dsl.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachine.kt
sample/android/src/main/java/com/freeletics/flowredux/compose/ComposeActivity.kt
sample/android/src/main/java/com/freeletics/flowredux/compose/PopularRepositoriesUi.kt

As discussed in #279 :
- removing initial state from state machine. Maybe we can find some middle ground in the future between #279 and this PR but I think for now it is best to make it "predictable" and simplified by removing this.
- Uses `null` as initial state for `produceState() ` i.e. used by `rememberState()` and `rememberStateAndDispatch()`. I have mixed feelings about it. On one hand I don't like working with `null` too much and would prefer usually something more descriptive, but on the other hand introducing some linke sealed interface just to be more descriptive seems like an overkill to me. I played around in my head with something like this: 
```kotlin
public sealed interface FlowReduxState<S : Any>
/**
* Indicates that no state has been emitted by the [FlowReduxStateMachine] …
```

Removed initial state and use `null` as initial state in compose

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/InStateSideEffectBuilder.kt

Reduces the scope of our try/catch to just the casting of `currentState` to avoid that actual issues with the call to `block` are swallowed. Real world case that happened to us: We have a `Flow<Foo>` to which we emit `Foo` after reading it as `Parcelable` from a `Bundle`. However the function that reads and emits `Foo` is actually generic so it's just operating with a `T : Parcelable`. Because of type erasure there is no type check happening here so whatever parcelable is in the bundle will be emitted, even if it is not `Foo`. When the `Flow` then has no other transform and is used directly with `collectWhileInState` the first type check happens when our handler is called which expects `Foo` as parameter. This happens inside `block` so the `ClassCastException` there is swallowed. From a …

don't swallow ClassCastExceptions from the handler

---

.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml

Makes trying out things from easier by not just using `main` for snapshots. The naming scheme is `[branch]-SNAPSHOT` (so main publishes `main-SNAPSHOT`) and `pr[pull request number]-SNAPSHOT`.

publish snapshots from all branches and prs

---

dependencies.gradle

AGP depends on an old version of Dokka which causes this incompatibility. Downgrade dokka for now until AGP 7.3.0 fixes it.

fix broken dokka

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/ChangeState.kt

I tried to create the `abstract fun reduce` directly in `ChangeState<out S>` but that won't work with the `out`. Removing that would mean that you can't return a more concrete `ChangeState<SubState>` anymore and adding the `out` to the lambdas (`(...) -> ChangeState<out S>`) leads to other compiler issues. So I went with just making the extension public. It was probably public before and I might have changed to internal without considering testing when introducing the explicit visibilty

make reduce public for testing purposes

---

README.md
docs/gettingstarted.md

Found a couple of typos while reading your docs 👍 Sending over the fixes

Fix minor typos on documentation

---

.github/workflows/publish-snapshot.yml

Will test that this actually works with one of the open dependabot prs

skip publishing snapshots when secrets are not available

---

docs/gettingstarted.md

Hi, nice library I have started to play with it but during the documentations reading I spotted a couple of typo inside the sample, hope helps.

doc: fixed some typos inside doc's samples

---

.github/workflows/publish-docs.yml
gradle/wrapper/gradle-wrapper.properties

This makes the gh pages branch obsolete. Instead of building the site and pushing it to that branch the action uploads it and triggers a deployment. We've been using it in mad for a while now https://github.com/freeletics/mad/blob/main/.github/workflows/publish-docs.yml

deploy website directly from github actions

---

flowredux/api/flowredux.api
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/StartStateMachineOnActionInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/StartStatemachineOnEnterSideEffectBuilder.kt
gradle/wrapper/gradle-wrapper.properties

My idea is to migrate some bigger older state machines in our code base to flow redux gradually by making them a sub state machine of the flow redux replacement. To make that possible all sub state machine dsl methods now get `StateMachine` instead of `FlowReduxStateMachine`. Since it is a super interface the change should be binary compatible.

allow any StateMachine to be a sub state machine

---

flowredux/api/flowredux.api
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/ChangedState.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/FlowReduxStoreBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/StartStateMachineOnActionInStateSideEffectBuilder.kt
gradle/wrapper/gradle-wrapper.properties

With this these methods that only exist to be called from the reified inline methods are hidden from auto completion since they are internal but still accessible to the inline functions. This is a binary compatible change (see `flowredux.api` file, the change there comes from removing the `@JvmSynthetic`)

make methods with KClass parameter internal with @PublishedApi

---

.github/workflows/build.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
CHANGELOG.md
README.md
RELEASING.md
gradle.properties

With this it is not neccessary to push commits to `main` anymore to do a release and as much as possible is automated. The remaining steps are:
1. update changelog (through a pr), we could probably also have some automation here but I personally don't like these auto generated changelogs
2. create and push a tag for the new version
To make this possible there are a few changes:
- we now have a `CHANGELOG.md` file comitted to the repo
- the release workflow will extract the section for the new release and automatically create a Github release with it
- `VERSION_NAME` is not comitted anymore and instead always computed
- for releases we tag the tag name as version
- for snapshots we take the last tag increment the last number by 1 and then append SNAPSHOT
- the readme contains …

automate more parts of the publishing process

---

flowredux/src/commonTest/kotlin/com/freeletics/flowredux/FlowReduxTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CollectWhileInStateTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/CustomIsInStateDslTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/FlowReduxStateMachineTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnEnterTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/ReducerTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/StartStateMachineOnActionInStateTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/SubStateMachineTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/internal/SubStateMachinesMapTest.kt

In preparation for adding Kotlin/JS as a target all tests need to be renamed because spaces in method names are not supported for Kotlin/JS. They are not as nice as before but there is not much we can do.

rename all tests

---

flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt

These were flaky because the state emission might happen before the new state is fully propagated internally, so while we receive `assertEquals(TestState.S2, awaitItem())` the cancellation of the old state might not have happened yet. The `signal.close()` might then also happen before that which causes `reached` to become `true`. The delay isn't nice but it causes the internal coroutines before which then causes the block to be cancelled during the delay. (note that this is not a real time delay, just virtual time in the test scheduler, so the time value there doesn't matter). I've tested both of them by running them 1k times each.

fix flaky tests

---

flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt

The problem with the previous implementation was that it can take a few ms for FlowRedux to cancel the `on<Action> {...}` block. therefore we have introduced the  `delay(100)` but since we did `advanceUntilIdle()` and `runCurrent()` on the `TestDispatcher` it skips the delay and it was sometimes still too fast (so cancelation happened afterward). That resulted in a flaky test.
Now I rephrased the test towards "Block is canceled within 10 milliseconds after having moved to another state"

Fix flaky on Test: actionBlockStopsWhenMovedToAnotherState

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/CoroutineWaiter.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/internal/StartStateMachineOnActionInStateSideEffectBuilder.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/internal/SubStateMachinesMapTest.kt

Follow up on #482 , this time for the `onActionStartStateMachine()` DSL block.
Uses `CoroutineWaiter()` to synchronize coroutines for collecting state and dispatching actions to sub statemachine. It basically ensures that substatemachine.state is collected before dispatching any action to substatemachine.

onActionStartStateMachine():  Make sure SubStateMachine State Flow is collected before dispatching actions to it

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/Action.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectInStateBasedOnStateBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectInStateBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/InStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnActionInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnEnterInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/StartStateMachineOnActionInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/StartStatemachineOnEnterSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/util/MapToIsInState.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/util/WhileInState.kt

We'll need to split state checks into 2 different kinds:
- One for checking whether we should start this side effect, this will match the current checks
- The other one for whether we should terminate the side effect. For the current things this will be the same but for anything inside the identity block this will need to check that the identity of the current state is still the same as the identity of the state that started the side effect. The reason for separating `isInState` for this purpose is to avoid reimpleting all side effects again for the identity block.
To avoid mistakes I want to have 2 separate interfaces for these 2. This introduces the first one that just matches the current checks. The second one will be introduced further into the refactoring. 
`InStateSideEffectBuilder` …

create IsInState interface, add val for it to InStateSideEffectBuilder

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectInStateBasedOnStateBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectInStateBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/InStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnActionInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnEnterInStateSideEffectBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/StartStatemachineOnEnterSideEffectBuilder.kt

Similar to `runOnlyIfInInputState` we now have a reusable method to produce a flow that emits a state change in the builder. This replaces the various versions of `setStateFlow` in the subclasses.

add reusable stateChange to InStateSideEffectBuilder

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/Action.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectWhile.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/CollectWhileBasedOnState.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnAction.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnActionStartStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnEnter.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnEnterStartStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/SideEffect.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/util/MapToIsInState.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/util/WhileInState.kt

With this `SideEffect` will directly emit `ChangedState` instead of the action. This completely separates the input and output of side effects and makes handling them easier. `Action` also doesn't need a state type paremeter anymore. So the flow is now `A -> Action<A> -> SideEffect -> ChangedState<S> -> Reducer -> S` with the extra that the reducer sends `InitialStateAction` whenever there is a new state.
There is still wrapping in another class going on internally (see `guardWithIsInState`), if the `ChangedState` object is not a `NoStateChange`, to continue having the reduce guarded by an `isInState` check. So this is only slightly more efficient allocation wise. I think it should be possible later to directly have this inside the originally created `ChangedState`, but it will require …

remove ChangeStateAction

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnAction.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/SideEffect.kt

Introduces `ActionBasedSideEffect` as subclass for `SideEffect` that makes a `Flow` of actions available. `OnAction` simply filters this flow and then runs the handler on it. 
`ActionBasedSideEffect` will also be used by the 2  sub state machine side effects.

refactor OnAction side effect

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/BaseBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/OnEnter.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/SideEffect.kt

`ManagedSideEffect` will now pass the state that caused the side effect to start to the builder when creating the side effect. We then pass that directly to `OnEnter` which doesn't need to collect anything at all with this.
Having the `initialState` as builder parameter will also allow us to modify add the identity of the initial state to `SideEffect.IsInState` so that they can get cancelled on changes.

refactor OnEnter side effect

---

flowredux/api/flowredux.api
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/BaseBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/ConditionBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/IdentityBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/ConditionBlockTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/IdentityBlockTest.kt

Closes #480 
With all the ground work that already happened in the refactorings this is now pretty simple. `sideEffectIsInState` where we create the `SideEffect.IsInState` based on `SideEffectBuilder.IsInState` now gets the `initialState` as parameter. The new `IdentityBuilderBlock` overrides that function and in addition to the regular isInState check will check that the identity of the given state matches the identity of the initial state. And that is pretty much it, the only other change was to add `untilIdentityChanges` to `InStateBuilderBlock` and `ConditionBuilderBlock`.

implement untilIdentityChanges block

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/sideeffects/SideEffect.kt

With the old collectWhileInState builder being gone, none of the side effects needs to react to state changes. So `sendState` can be removed and I've renamed `sendStateChange` to `startIfNeeded` which is the only thing it does now and matches `cancelIfNeeded`

remove sendState from side effect, rename sendStateChange

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/ConditionBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/IdentityBuilderBlock.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux/dsl/InStateBuilderBlock.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/StateAndAction.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/dsl/IdentityBlockTest.kt

Closes #546 
The tests are basically just a copy of the existing tests with null values.

allow identity to be null

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux/sideeffects/OnActionTest.kt

The reduxStore has a lock so that [state changes](https://github.com/freeletics/FlowRedux/blob/main/flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt#L40-L50)) and [handling actions](
https://github.com/freeletics/FlowRedux/blob/main/flowredux/src/commonMain/kotlin/com/freeletics/flowredux/FlowRedux.kt#L56-L60) don't happen at the same time which could result in actions being processed when we stop a side effect or actions being dropped while changing to the new state where they would actually be handled. The deadlock then happens because the state change from the first of the 2 actions waits at the lock entry while the second action is being processed. However the processing of the second action never finishes because it suspends when trying to add the second state …

fix deadlock for ordered ExecutionPolicy

---

flowredux/api/flowredux.api
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/State.kt

This only existed for backwards compatibility and isn't needed anymore.

remove JvmName

---

flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/BaseBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/CollectWhile.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/OnAction.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/OnActionStartStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/OnEnter.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterStartStateMachine.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/ConditionBlockTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/IdentityBlockTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/CollectWhileEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/CollectWhileTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnActionEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnActionStartStateMachineTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnActionTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterStartStateMachineTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterTest.kt
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux2/sample/shared/MarkAsFavoriteStateMachine.kt
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux2/sample/shared/PaginationStateMachine.kt

All DSL handlers now have either `State<S>` or `ChangeableState<S>` as receiver to create a more uniform API and make the DSL less noisy.
Before:
```kotlin
onEnter { it.mutate { ... } }
onEnterEffect { ... }
on<Action> { action, state -> state.mutate { ... } }
onActionEffect<Action> { action, state -> ... }
// collectWhileInState etc are like the action handlers
```
After:
```kotlin
onEnter { mutate { ... } }
onEnterEffect { ... }
on<Action> { mutate { ... } }
onActionEffect<Action> { ... }
// collectWhileInState etc are like the action handlers
```
- `State` access now always happens through `this`
- Other parameters like an action are always the only parameter and can be easily accessed through `it`.
- Unused parameters can be easily ignored, previously you'd very often have `action, _ …

change State wrapper to be receiver of all DSL handlers

---

flowredux/api/flowredux.api
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/BaseBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/ChangeableState.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/ConditionBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/FlowReduxBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/FlowReduxDsl.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/IdentityBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/InStateBuilder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/util/FlowReduxDsl.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterStartStateMachineTest.kt
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux2/sample/shared/PaginationStateMachine.kt

This will prevent 2 things
Calling a mutator inside a mutator:
```kotlin
on<Foo> {
override {
mutate { // fails
}
}
}
```
Accessing `snapshot` inside a mutator:
```kotlin
on<Foo> {
override {
snapshot.copy(...) // fails
}
}
```
Especially the latter is helpful with avoiding common mistakes were a potentially outdated state is used to construct the new state instead of using the state that is passes as `this` in the mutator. It doesn't solve it completely since you could still build a new state from the snapshot outside of the mutator and then use it but better than what we had before.
Also makes the DSL marker annotation internal.

add DSL marker to State in mutators

---

compose/api/compose.api
compose/src/commonMain/kotlin/com/freeletics/flowredux2/compose/ComposeFlowReduxStateMachine.kt
flowredux/api/flowredux.api
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/FlowReduxStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/FlowReduxStateMachineFactory.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/LegacyFlowReduxStateMachine.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/sideeffects/ReduxStore.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/FlowReduxStateMachineTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/StateMachine.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/CollectWhileEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterEffectTest.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/sideeffects/OnEnterStartStateMachineTest.kt
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux2/sample/shared/MarkAsFavoriteStateMachine.kt
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux2/sample/shared/PaginationStateMachine.kt

Introduces `FlowReduxStateMachineFactory` as the class to implement and write the DSL, there is a `launchIn(CoroutineScope)` method that then returns a `FlowReduxStateMachine` which holds an active (but lazily started) `StateFlow`. 
The 2 main advantages are:
- It is easier to observe an instance of the state machine in multiple places.
- The internal input actions channel is unique per `FlowReduxStateMachine` instance. This way we don't need the checks in dispatch whether the state machine is being collected. When you obtain an instance through `launchIn` it's active and you can send actions into it. In case it's not being collected right now they are buffered in the channel.
Closes #654 which was the original motivation and highlights the issue a bit more.
Notes:
- The previous …

introduce FlowReduxStateMachineFactory

---

flowredux/api/flowredux.api
flowredux/flowredux.gradle.kts
flowredux/src/androidMain/kotlin/com/freeletics/flowredux2/AndroidSavedStateHolder.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/FlowReduxStateMachineFactory.kt
flowredux/src/commonTest/kotlin/com/freeletics/flowredux2/StateMachine.kt
flowredux/src/composeMain/kotlin/com/freeletics/flowredux2/ComposeFlowReduxStateMachine.kt
flowredux/src/composeMain/kotlin/com/freeletics/flowredux2/SaveableStateHolder.kt
gradle/libs.versions.toml
sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux2/sample/shared/PaginationStateMachine.kt

Brings our internal state machine subclasses into the open. Instead of being an extra class this is now built directly into `FlowReduxStateMachineFactory` and allows having state machines that
- behave like right now and always start from the given initial state (`lossyStateHolder`)
- start from the last observed state (`inMemoryStateHolder`)
- start from a state saved to a `SavedStateHandle` (`savedStateHandleStateHolder `, `serializableStateHolder`, `parcelableStateHolder`)
I first thought about making one of these the default but it's hard to choose between `lossyStateHolder` and `inMemoryStateHolder`.
Example:
```
class MyFactory(...) : FlowReduxStateMachineFactory(lossyStateHolder(InitialState)) {}
```

add state saving mechanisms to StateMachine

---

flowredux/flowredux.gradle.kts
flowredux/src/androidMain/kotlin/com/freeletics/flowredux2/util/AtomicCounter.kt
flowredux/src/commonMain/kotlin/com/freeletics/flowredux2/FlowReduxStateMachineFactory.kt
gradle.properties

- Fixes warning that `androidMain` shouldn't depend on `jvmMain` by removing the dependency. Because of that I needed to create a copy of `AtomicCounter`. The alternative would have been to create a shared source set and make both `jvmMain` and `androidMain` depend on it. Just for one class it's not worth it though and the class will also go away once the atomic APIs in the stdlib go stable.
- Suppresses the warning for `IncorrectCompileOnlyDependencyWarning` because we intentionally do the `compileOnly` dependency even if it's not supported for Kotlin/Native and JS. We expect Kotlin consumers of this library that use `SavedStateHandle` to bring in the dependency.

fix build warning for source set dependency and compileOnly dependency
